/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.NumerosComplejos;
import javax.swing.JOptionPane;

/**
 *
 * @author Lorenzo
 */
public class ObjetoTres extends javax.swing.JFrame {

    /**
     * Creates new form ObjetoTres
     */
    public ObjetoTres() {
        initComponents();
        txtReal1.setEditable(true);
        txtImaginaria1.setEditable(true);
        txtReal2.setEditable(true);
        txtImaginaria2.setEditable(true);
        cmbOperacion.setEnabled(true);
        cmdCalcular.setEnabled(true);
        cmdLimpiar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbOperacion = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtReal1 = new javax.swing.JTextField();
        txtImaginaria1 = new javax.swing.JTextField();
        txtImaginaria2 = new javax.swing.JTextField();
        txtReal2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtReal3 = new javax.swing.JTextField();
        cmdCalcular = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        txtImaginaria3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NÚMEROS COMPLEJOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 130, 30));

        jLabel2.setText("Parte Real:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, 40));

        cmbOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suma", "Resta", "Multiplicación", "División" }));
        jPanel1.add(cmbOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 90, 70, 30));

        jLabel3.setText("Parte Imaginaria:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 90, 40));

        jLabel4.setText("Parte Real:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 90, 40));

        jLabel5.setText("Parte Imaginaria:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 90, 40));

        txtReal1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtReal1KeyTyped(evt);
            }
        });
        jPanel1.add(txtReal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 60, -1));

        txtImaginaria1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImaginaria1KeyTyped(evt);
            }
        });
        jPanel1.add(txtImaginaria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 60, -1));

        txtImaginaria2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImaginaria2KeyTyped(evt);
            }
        });
        jPanel1.add(txtImaginaria2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 60, -1));

        txtReal2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtReal2KeyTyped(evt);
            }
        });
        jPanel1.add(txtReal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 60, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Resultado:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 90, 30));

        txtReal3.setEditable(false);
        jPanel1.add(txtReal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 80, 30));

        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 90, 30));

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 90, 30));

        txtImaginaria3.setEditable(false);
        jPanel1.add(txtImaginaria3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(533, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
        int r1,i1,r2,i2,op;
        NumerosComplejos c1,c2,c3=null;
        if(txtReal1.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Espacio vacío, favor llenarlo", "ERROR",JOptionPane.ERROR_MESSAGE);
            txtReal1.setEditable(true);
            cmbOperacion.setEnabled(true);
        cmdCalcular.setEnabled(true);
        cmdLimpiar.setEnabled(true);
            txtReal1.requestFocusInWindow();
            
        }else if(txtImaginaria1.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Espacio vacío, favor llenarlo", "ERROR",JOptionPane.ERROR_MESSAGE);
            txtImaginaria1.setEditable(true);
            cmbOperacion.setEnabled(true);
        cmdCalcular.setEnabled(true);
        cmdLimpiar.setEnabled(true);
            txtImaginaria1.requestFocusInWindow();
            
        }else if(txtReal2.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Espacio vacío, favor llenarlo", "ERROR",JOptionPane.ERROR_MESSAGE);
            txtReal2.setEditable(true);
            cmbOperacion.setEnabled(true);
        cmdCalcular.setEnabled(true);
        cmdLimpiar.setEnabled(true);
            txtReal2.requestFocusInWindow();
            
        }else if(txtImaginaria2.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Espacio vacío, favor llenarlo", "ERROR",JOptionPane.ERROR_MESSAGE);
            txtImaginaria2.setEditable(true);
            cmbOperacion.setEnabled(true);
        cmdCalcular.setEnabled(true);
        cmdLimpiar.setEnabled(true);
            txtImaginaria2.requestFocusInWindow();
            
        }else{
            op = cmbOperacion.getSelectedIndex();
            r1 = Integer.parseInt(txtReal1.getText());
            i1 = Integer.parseInt(txtImaginaria1.getText());
            r2 = Integer.parseInt(txtReal2.getText());
            i2 = Integer.parseInt(txtImaginaria2.getText());
            
            c1 = new NumerosComplejos(r1,i1);
            c2 = new NumerosComplejos(r2,i2);
            
            switch(op){
                case 0:
                    c3 = c1.suma(c2);
                    break;
                case 1:
                    c3 = c1.resta(c2);
                    break;
                case 2:
                    c3 = c1.multiplicacion(c2);
                    break;
                case 3:
                    c3 = c1.division(c2);
                    break;
            }txtReal3.setText(""+c3.getReal());
            txtImaginaria3.setText(""+c3.getImaginaria());
            
            txtReal1.setEditable(false);
        txtImaginaria1.setEditable(false);
        txtReal2.setEditable(false);
        txtImaginaria2.setEditable(false); 
            cmbOperacion.setEnabled(false);
        cmdCalcular.setEnabled(false);
        cmdLimpiar.setEnabled(true);
        }
        
       
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        txtReal1.setText("");
        txtImaginaria1.setText("");
        txtReal2.setText("");
        txtImaginaria2.setText("");
        txtReal3.setText("");
        txtImaginaria3.setText("");
        cmbOperacion.setSelectedIndex(0);
        txtReal1.requestFocusInWindow();
     
        
        txtReal1.setEditable(true);
        txtImaginaria1.setEditable(true);
        txtReal2.setEditable(true);
        txtImaginaria2.setEditable(true);
        cmbOperacion.setEnabled(true);
        cmdCalcular.setEnabled(true);
        cmdLimpiar.setEnabled(false);
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void txtReal1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReal1KeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtReal1KeyTyped

    private void txtImaginaria1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImaginaria1KeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtImaginaria1KeyTyped

    private void txtReal2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReal2KeyTyped
      char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtReal2KeyTyped

    private void txtImaginaria2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImaginaria2KeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtImaginaria2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObjetoTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObjetoTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObjetoTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObjetoTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ObjetoTres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOperacion;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtImaginaria1;
    private javax.swing.JTextField txtImaginaria2;
    private javax.swing.JTextField txtImaginaria3;
    private javax.swing.JTextField txtReal1;
    private javax.swing.JTextField txtReal2;
    private javax.swing.JTextField txtReal3;
    // End of variables declaration//GEN-END:variables
}
